### ISSUE TITLE
还在维护吗？

### ISSUE THREAD

**Issue by lys623** [Changlon/koa-wechat-public#2]
1.怎么没有主动回复信息的接口？
2.如何设置信息default处理逻辑？

**Comment by Changlon** [comment]
主动推送信息在 Send模块下的 pushTxtCustomerMsg 方法，这个库是我两年前做的，不是太完善，但是工作上的大部分功能都能应用，后期也写了多公众号管理模块没有开源。有兴趣可以提交pr

**Comment by Changlon** [comment]
开始正式维护了，这个项目准备开源继续做下去，后续准备提供一些开箱即用的微信公众号开发模版
